
#mutationtype: ["insertion", "deletion"]
mutationtype: ["A2C", "A2G", "A2T", "C2A", "C2G", "C2T", "insertion", "deletion"]
variationtype: ["snv","indel"]
#path to diferent mutation files
mutationfiles: {A2C: "../../MakeLogRegInput/annotated_datasets/combined6/A2C_GC_repli_recomb_meth_0.002_all3_long_hg38.dat.gz",
A2G: "../../MakeLogRegInput/annotated_datasets/combined6/A2G_GC_repli_recomb_meth_0.002_all3_long_hg38.dat.gz",
A2T: "../../MakeLogRegInput/annotated_datasets/combined6/A2T_GC_repli_recomb_meth_0.002_all3_long_hg38.dat.gz",
C2A: "../../MakeLogRegInput/annotated_datasets/combined6/C2A_GC_repli_recomb_meth_0.002_all3_long_hg38.dat.gz", 
C2G: "../../MakeLogRegInput/annotated_datasets/combined6/C2G_GC_repli_recomb_meth_0.002_all3_long_hg38.dat.gz",
C2T: "../../MakeLogRegInput/annotated_datasets/combined6/C2T_GC_repli_recomb_meth_0.002_all3_long_hg38.dat.gz",
insertion: "../../MakeLogRegInput/annotated_datasets/combined6/insertion_GC_repli_recomb_meth_0.002_long_hg38.dat.gz",
deletion: "../../MakeLogRegInput/annotated_datasets/combined6/deletion_GC_repli_recomb_meth_0.002_long_hg38.dat.gz"
}

####Kmerpapa crossvalidation
penalty_values: [1,5,10,15,20] # also complexity
alpha_values: [1,5] # aslo pseudo count

#paths to possible Lof files 
possible_variants_path: {A2C: "../../MakeLogRegInput/possible_variants/split_SNV_LoF/unzipped_sorted/A2C.gencode_v42_LoF_SNVs_sorted.txt",
A2G: "../../MakeLogRegInput/possible_variants/split_SNV_LoF/unzipped_sorted/A2G.gencode_v42_LoF_SNVs_sorted.txt",
A2T: "../../MakeLogRegInput/possible_variants/split_SNV_LoF/unzipped_sorted/A2T.gencode_v42_LoF_SNVs_sorted.txt",
C2A: "../../MakeLogRegInput/possible_variants/split_SNV_LoF/unzipped_sorted/C2A.gencode_v42_LoF_SNVs_sorted.txt", 
C2G: "../../MakeLogRegInput/possible_variants/split_SNV_LoF/unzipped_sorted/C2G.gencode_v42_LoF_SNVs_sorted.txt",
C2T: "../../MakeLogRegInput/possible_variants/split_SNV_LoF/unzipped_sorted/C2T.gencode_v42_LoF_SNVs_sorted.txt"
}

annotated_variants_path: {A2C: "../../MakeLogRegInput/annotated_datasets/all_possible/A2C_GC_repli_recomb_meth_0_long_hg38.dat.gz",
A2G: "../../MakeLogRegInput/annotated_datasets/all_possible/A2G_GC_repli_recomb_meth_0_long_hg38.dat.gz",
A2T: "../../MakeLogRegInput/annotated_datasets/all_possible/A2T_GC_repli_recomb_meth_0_long_hg38.dat.gz",
C2A: "../../MakeLogRegInput/annotated_datasets/all_possible/C2A_GC_repli_recomb_meth_0_long_hg38.dat.gz", 
C2G: "../../MakeLogRegInput/annotated_datasets/all_possible/C2G_GC_repli_recomb_meth_0_long_hg38.dat.gz",
C2T: "../../MakeLogRegInput/annotated_datasets/all_possible/C2T_GC_repli_recomb_meth_0_long_hg38.dat.gz",
insertion: "../output/PossibleVariants/insertion_possible_lof.tsv.gz",
deletion: "../output/PossibleVariants/deletion_possible_lof.tsv.gz"
}

mut_translations: {A2C: ["snv","",""],
A2G: ["snv","",""],
A2T: ["snv","",""],
C2A: ["snv","",""], 
C2G: ["snv","",""],
C2T: ["snv","",""],
insertion: ["indel", "--sample", "ins"], #importent!!!!!!!
deletion: ["indel", "--sample","del_start"] #importent!!!!!!!
}

bck_kmer: {snv: "-r 4",
indel: "--before_after 4 3"
}

#xcxc|x|cxc # how indel_kmers are decidedd

logmodel: ["nobeta","intercept"]

#gfeatures: ["repli","GC_1k","recomb_decode","CpG_I","meth"]

#for haploinsufficiency

#for compareing different models
models: ["kmer", "genomic","both"] # have to find another name for the full/complex model


#resources
#gencode : "../resources/gencode.v44.annotation.gtf.gz"
gencode: "../resources/gencode.v42.annotation.gtf.gz"
hg382bit:  "../resources/hg38.2bit"
hg38bedfile: "../resources/hg38.bed" ## this should change or be double checked. it was just somethig i had laying around
annotation_parameters: ../../MakeLogRegInput/parameter_files/hg38/GC_repli_recomb_meth.txt # hardcoded at the moment