
#mutationtype: ["insertion", "deletion"]
mutationtype: ["A2C", "A2G", "A2T", "C2A", "C2G", "C2T", "insertion", "deletion"]
variationtype: ["snv","indel"]
chromosomes: ["chr1","chr2","chr3","chr4","chr5","chr6","chr7","chr8","chr9","chr10","chr11","chr12", "chr13","chr14","chr15","chr16","chr17","chr18", "chr19","chr20","chr21","chr22"]
# check how many chromosome other species have
#path to diferent mutation files
mutationfiles: {A2C: "../resources/mutations/dnm/a2c_dnm.tsv",
A2G: "../resources/mutations/dnm/a2g_dnm.tsv",
A2T: "../resources/mutations/dnm/a2t_dnm.tsv",
C2A: "../resources/mutations/dnm/c2a_dnm.tsv", 
C2G: "../resources/mutations/dnm/c2g_dnm.tsv",
C2T: "../resources/mutations/dnm/c2t_dnm.tsv",
insertion: "../resources/mutations/dnm/insertion_dnm.tsv",
deletion: "../resources/mutations/dnm/deletion_dnm.tsv"
}

atac,h3k9me3,h3k36me3,meth1,meth2,meth3,recomb,GC1k,CpG_I,repli1
####Kmerpapa crossvalidation
penalty_values: [1,5,7,8,9,10,12,13,14,15,17,20,21] # also complexity
alpha_values: [1] # also pseudo count

genomic_features: ["meth", ""]
#paths to possible Lof files 
possible_variants_path: {A2C: "../../MakeLogRegInput/possible_variants/split_SNV_LoF/unzipped_sorted/A2C.gencode_v42_LoF_SNVs_sorted.txt",
A2G: "../../MakeLogRegInput/possible_variants/split_SNV_LoF/unzipped_sorted/A2G.gencode_v42_LoF_SNVs_sorted.txt",
A2T: "../../MakeLogRegInput/possible_variants/split_SNV_LoF/unzipped_sorted/A2T.gencode_v42_LoF_SNVs_sorted.txt",
C2A: "../../MakeLogRegInput/possible_variants/split_SNV_LoF/unzipped_sorted/C2A.gencode_v42_LoF_SNVs_sorted.txt", 
C2G: "../../MakeLogRegInput/possible_variants/split_SNV_LoF/unzipped_sorted/C2G.gencode_v42_LoF_SNVs_sorted.txt",
C2T: "../../MakeLogRegInput/possible_variants/split_SNV_LoF/unzipped_sorted/C2T.gencode_v42_LoF_SNVs_sorted.txt"
}

annotated_variants_path: {A2C: "../../MakeLogRegInput/annotated_datasets/all_possible/A2C_GC_repli_recomb_meth_0_long_hg38.dat.gz",
A2G: "../../MakeLogRegInput/annotated_datasets/all_possible/A2G_GC_repli_recomb_meth_0_long_hg38.dat.gz",
A2T: "../../MakeLogRegInput/annotated_datasets/all_possible/A2T_GC_repli_recomb_meth_0_long_hg38.dat.gz",
C2A: "../../MakeLogRegInput/annotated_datasets/all_possible/C2A_GC_repli_recomb_meth_0_long_hg38.dat.gz", 
C2G: "../../MakeLogRegInput/annotated_datasets/all_possible/C2G_GC_repli_recomb_meth_0_long_hg38.dat.gz",
C2T: "../../MakeLogRegInput/annotated_datasets/all_possible/C2T_GC_repli_recomb_meth_0_long_hg38.dat.gz",
insertion: "../output/PossibleVariants/insertion_possible_lof.tsv.gz",
deletion: "../output/PossibleVariants/deletion_possible_lof.tsv.gz",
insertion: "",
deletion: ""
}

mut_translations: {A2C: ["snv","",""],
A2G: ["snv","",""],
A2T: ["snv","",""],
C2A: ["snv","",""], 
C2G: ["snv","",""],
C2T: ["snv","",""],
insertion: ["indel", "--sample", "ins"], #importent!!!!!!!
deletion: ["indel", "--sample","del_start"] #importent!!!!!!!
}

bck_kmer: {snv: "-r 4",
indel: "--before_after 4 3"
}

#xcxc|x|cxc # how indel_kmers are decidedd

logmodel: ["nobeta","intercept"]

#gfeatures: ["repli","GC_1k","recomb_decode","CpG_I","meth"]

#for haploinsufficiency

#for compareing different models
models: ["kmer", "genomic","both"] # have to find another name for the full/complex model


#resources
transcripts_gff3: "../resources/gencode.v42.annotation.gff3.gz"
transcripts_gtf: "../resources/gencode.v42.annotation.gtf.gz"

hg382bit:  "../resources/hg38.2bit"
hg38bedfile_strict: "../resources/20160622.allChr.mask_noXY.bed" ## this should change or be double checked. it was just somethig i had laying around
#hg38bedfile_full: "../resources/hg38.bed"
annotation_parameters: ../resources/annotationtracks.txt
#annotation_parameters: ../../MakeLogRegInput/parameter_files/hg38/GC_repli_recomb_meth.txt # hardcoded at the moment

# cd ~/nnPib2021/group_POB && echo "files ..." && chmod -f -R u+rw,g+rw,o+rw . 
# cd ~/nnPib2021/group_POB && echo "dirs ..."  && find . -type d -exec chmod -f -s,o+rw {} \;