
type : ["A2C", "A2G", "A2T", "C2A", "C2G", "C2T", "insertion", "deletion"]
#path to diferent mutation files
mutation_files: {A2C: "../../MakeLogRegInput/annotated_datasets/combined6/A2C_GC_repli_recomb_meth_0.002_all3_long_hg38.dat.gz",
A2G: "../../MakeLogRegInput/annotated_datasets/combined6/A2G_GC_repli_recomb_meth_0.002_all3_long_hg38.dat.gz",
A2T: "../../MakeLogRegInput/annotated_datasets/combined6/A2T_GC_repli_recomb_meth_0.002_all3_long_hg38.dat.gz",
C2A: "../../MakeLogRegInput/annotated_datasets/combined6/C2A_GC_repli_recomb_meth_0.002_all3_long_hg38.dat.gz", 
C2G: "../../MakeLogRegInput/annotated_datasets/combined6/C2G_GC_repli_recomb_meth_0.002_all3_long_hg38.dat.gz",
C2T: "../../MakeLogRegInput/annotated_datasets/combined6/C2T_GC_repli_recomb_meth_0.002_all3_long_hg38.dat.gz",
insertion: "../../MakeLogRegInput/annotated_datasets/combined6/insertion_GC_repli_recomb_meth_0.002_long_hg38.dat.gz",
deletion: "../../MakeLogRegInput/annotated_datasets/combined6/deletion_GC_repli_recomb_meth_0.002_long_hg38.dat.gz"
}

log_model: ["intercept", "nobeta"]

g_features: ["repli","GC_1k","recomb_decode","CpG_I","meth"]


#for haploinsufficiency

#for compareing different models
models: ["kmer", "genomic","both"] # have to find another name for the full/complex model

gencode : "../resources/gencode.v44.annotation.gtf.gz"